baseURL = "https://practivio.com/"
title = "Practivio"
theme = "PaperMod"
canonifyURLs = true
enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  filename   = "sitemap.xml"
  priority   = 0.5

[pagination]
pagerSize = 10

[params]
mainSections = []
description = "Shop Smart. Live Better."
author = "Practivio"
defaultTheme = "auto"
showReadingTime = true
showBreadCrumbs = true
 env = "production"
