[[headers]]
for = "/sitemap.xml"
  [headers.values]
  Content-Type = "application/xml; charset=utf-8"

[[headers]]
for = "/sitemaps/*"
  [headers.values]
  Content-Type = "application/xml; charset=utf-8"
